apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
spec:
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
        app.kubernetes.io/version: 44e1877
        app.kubernetes.io/part-of: easytrade
        dt.owner: team-workshop
    spec:
      containers:
        - name: loginservice
          image: gcr.io/dynatrace-demoability/easytrade/loginservice:44e1877
          ports:
            - containerPort: 80
          env:
            - name: MSSQL_CONNECTIONSTRING
              value: "Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true"
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/part-of']
            - name: DT_RELEASE_STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loginservice
  labels:
    dt.owner: team-workshop
spec:
  type: ClusterIP
  selector:
    app: loginservice
  ports:
    - name: http
      port: 80
      targetPort: 80
