apiVersion: apps/v1
kind: Deployment
metadata:
  name: offerservice
spec:
  selector:
    matchLabels:
      app: offerservice
  template:
    metadata:
      labels:
        app: offerservice
        app.kubernetes.io/version: 44e1877
        app.kubernetes.io/part-of: easytrade
        dt.owner: team-workshop
    spec:
      containers:
        - name: offerservice
          image: gcr.io/dynatrace-demoability/easytrade/offerservice:44e1877
          ports:
            - containerPort: 8080
          env:
            - name: LOGIN_SERVICE_PORT
              value: "80"
            - name: LOGIN_SERVICE_BASE_URL
              value: loginservice
            - name: MANAGER_BASE_URL
              value: manager
            - name: MANAGER_PORT
              value: "80"
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/part-of']
            - name: DT_RELEASE_STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: offerservice
  labels:
    dt.owner: team-workshop
spec:
  type: ClusterIP
  selector:
    app: offerservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
