apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluginservice
spec:
  selector:
    matchLabels:
      app: pluginservice
  template:
    metadata:
      labels:
        app: pluginservice
        app.kubernetes.io/version: 44e1877
        app.kubernetes.io/part-of: easytrade
        dt.owner: team-workshop
    spec:
      containers:
        - name: pluginservice
          image: gcr.io/dynatrace-demoability/easytrade/pluginservice:44e1877
          ports:
            - containerPort: 8080
          env:
            - name: OFFER_SERVICE__PORT
              value: "8080"
            - name: OFFER_SERVICE__DOMAIN
              value: offerservice
            - name: MANAGER__DOMAIN
              value: manager
            - name: MANAGER__PORT
              value: "80"
            - name: DT_RELEASE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/part-of']
            - name: DT_RELEASE_STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 150m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pluginservice
  labels:
    dt.owner: team-workshop
spec:
  type: ClusterIP
  selector:
    app: pluginservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
